// Generated by AutoGenerateLayout

#ifndef _LAYOUT_INIT_H_
#define _LAYOUT_INIT_H_

#include "CLayout.h"

void InitLayout(CLayout& layout, CWnd* parent)
{
	layout.Initial(parent);
	
	//layout.RegisterControl(IDC_EDIT1, CLayout::e_stretch_all);
	//layout.RegisterControl(IDC_BUTTONCTRL, CLayout::e_stretch_all);
}

#endif