//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 HX.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HX_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDD_VISION                      129
#define IDD_MODBUS                      130
#define IDD_CAD                         131
#define IDI_ICON1                       142
#define IDI_GDUT                        142
#define IDR_MENU1                       143
#define IDI_CAD                         144
#define IDI_MODBUS                      145
#define IDI_VISION                      146
#define IDD_LOGIN                       147
#define IDD_CHANGEPWD                   149
#define IDD_DATABASE                    151
#define IDD_MONITOR                     153
#define IDB_HG                          156
#define IDI_BLUE                        157
#define IDI_RED                         158
#define IDI_ICON4                       159
#define IDI_YELLOW                      159
#define IDI_GRAY                        160
#define IDI_HIGHBLUE                    161
#define IDB_BITMAP1                     162
#define IDB_BITMAP2                     163
#define IDC_TAB1                        1000
#define IDC_COMBO1                      1001
#define IDC_COMBO2                      1002
#define IDC_COMBO3                      1003
#define IDC_COMBO4                      1004
#define IDC_COMBO5                      1005
#define IDC_EDIT1                       1006
#define IDC_BUTTON_OPEN                 1007
#define IDC_EDIT_PWD                    1007
#define IDC_EDIT3                       1007
#define IDC_BUTTON_SEND_ONCE            1008
#define IDC_EDIT4                       1008
#define IDC_EDIT2                       1010
#define IDC_BUTTON1                     1015
#define IDC_LIST1                       1016
#define IDC_BUTTON4                     1016
#define IDC_BUTTON_CANCEL               1016
#define IDC_DAT_LIST                    1016
#define IDC_LIST2                       1017
#define IDC_BUTTON2                     1018
#define IDC_MOD_BTN_CHANGE              1018
#define IDC_DAT_BTN_CLEAR               1018
#define IDC_STATIC1                     1021
#define IDC_STATIC2                     1022
#define IDC_STATIC3                     1023
#define IDC_STATIC4                     1024
#define IDC_STATIC5                     1025
#define IDC_STATIC6                     1026
#define IDC_STATIC7                     1027
#define IDC_STATIC8                     1028
#define IDC_STATIC9                     1029
#define IDC_PIC                         1030
#define IDC_BUTTON3                     1031
#define IDC_BUTTON_CLEAN                1032
#define IDC_STATIC_CAD_CHOOSE           1033
#define IDC_BUTTON_CAD_OPEN             1034
#define IDC_EDIT_CAD_PATH               1035
#define IDC_BUTTON_CAD_DRAW             1036
#define IDC_STATIC_CAD_DRAW             1037
#define IDC_STATIC_CAD_PIC              1038
#define IDC_LIST_CAD_LOC                1039
#define IDC_STATIC_CAD_LOC              1040
#define IDC_BUTTON_CAD_SEND             1041
#define IDC_STATIC10                    1042
#define IDC_STATIC11                    1043
#define IDC_STATIC12                    1044
#define IDC_LOGIN_USERNAME              1045
#define IDC_LOGIN_PWD                   1046
#define IDC_EDIT_USER                   1047
#define IDC_BUTTON_LOGIN                1048
#define IDC_VISION_BUTTON_LOG           1049
#define IDC_BUTTON_SETPWD               1049
#define IDC_VISION_BUTTON_EXIT          1050
#define IDC_USER_CHANGEPWD              1050
#define IDC_CAD_STATIC_NAME             1050
#define IDC_HX_STATIC_TITLE             1051
#define IDC_HX_BTN_VISION               1052
#define IDC_HX_BTN_CAD                  1053
#define IDC_HX_BTN_MODBUS               1054
#define IDC_HX_STATIC_GDUT              1055
#define IDC_VIS_BTN_OPCAD               1056
#define IDC_HX_STATIC_GDUT2             1056
#define IDC_VIS_BTN_OPMOD               1057
#define IDC_CAD_BTN_OPMOD               1057
#define IDC_HX_BTN_DATA                 1057
#define IDC_MOD_BTN_OPVS                1057
#define IDC_CAD_BTN_OPVS                1058
#define IDC_HX_BTN_MONITOR              1058
#define IDC_MOD_BTN_OPCAD               1058
#define IDC_VIS_BTN_OPMON               1058
#define IDC_CAD_BTN_OPMON               1059
#define IDC_VIS_BTN_OPDATA              1059
#define IDC_MOD_BTN_OPMON               1059
#define IDC_MOD_BTN_OPDATA              1060
#define IDC_CAD_BTN_OPDATA              1060
#define IDC_VIS_BTN_OPVS                1060
#define IDC_RADIO1                      1061
#define IDC_CAD_BTN_OPCAD               1061
#define IDC_MOD_BTN_OPMOD               1061
#define IDC_DAT_BTN_OPMON               1062
#define IDC_DAT_BTN_OPVS                1063
#define IDC_DAT_BTN_OPCAD               1064
#define IDC_DAT_BTN_OPMOD               1065
#define IDC_DATETIMEPICKER1             1066
#define IDC_DATETIMEPICKER2             1067
#define IDC_DAT_STATIC_TIME             1068
#define IDC_DAT_BTN_QUERY               1069
#define IDC_EDIT_TYPE                   1070
#define IDC_DATETIMEPICKER3             1070
#define IDC_STATIC13                    1071
#define IDC_DATETIMEPICKER4             1071
#define IDC_STATIC14                    1072
#define IDC_DAT_STATIC_TIMEEND          1072
#define IDC_MON_STATIC_PLC              1073
#define IDC_STATIC15                    1073
#define IDC_DAT_BTN_OPDAT               1073
#define IDC_MON_STATIC_GLUE             1074
#define IDC_STATIC16                    1074
#define IDC_MON_STATIC_STOP             1075
#define IDC_STATIC17                    1075
#define IDC_MON_STATIC_TYPE             1076
#define IDC_STATIC18                    1076
#define IDC_MON_STATIC_BATCH            1077
#define IDC_STATIC19                    1077
#define IDC_MON_EDIT_TYPE               1078
#define IDC_STATIC20                    1078
#define IDC_MON_EDIT_BATCH              1079
#define IDC_EDIT_XFLOOR                 1079
#define IDC_MON_STATIC_COORD            1080
#define IDC_EDIT_YFLOOR                 1080
#define IDC_MON_STATIC_X                1081
#define IDC_EDIT_THETAFLOOR             1081
#define IDC_MON_EDIT_X                  1082
#define IDC_MOD_PIC_HG                  1082
#define IDC_MON_EDIT_Y                  1083
#define IDC_EDIT_TYPE5                  1083
#define IDC_EDIT_THETACEILING           1083
#define IDC_MON_STATIC_Y                1084
#define IDC_EDIT_YCEILING               1084
#define IDC_MON_STATIC_THETA            1085
#define IDC_EDIT_XCEILING               1085
#define IDC_MON_EDIT_THETA              1086
#define IDC_MON_PIC_PLC                 1087
#define IDC_MON_PIC_GLUE                1088
#define IDC_MON_PIC_STOP                1089
#define IDC_MON_BTN_OPVS                1090
#define IDC_MON_BTN_OPCAD               1091
#define IDC_MON_BTN_OPDATA              1092
#define IDC_MON_BTN_OPMOD               1093
#define IDC_DAT_BTN_DELETE              1094
#define IDC_MON_BTN_OPMON               1094
#define IDC_DAT_STATIC_NAME             1095
#define IDC_VS_STATIC_NAME              1096
#define IDC_MON_STATIC_NAME             1097
#define IDC_MOD_STATIC_NAME             1098
#define IDC_DAT_STATIC2                 1099
#define IDC_DAT_STATIC1                 1101
#define IDC_HX_PIC_MAIN                 1102
#define IDC_MON_PIC_MAIN                1103
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_MENU_F1                      32779
#define ID_MENU_F2                      32780
#define ID_MENU_F3                      32781
#define ID_MENU_F4                      32782
#define ID_MENU_F5                      32783
#define ID_32790                        32790
#define ID_32791                        32791
#define ID_MENU_LOGIN                   32792
#define ID_MENU_EXIT                    32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
